### ISSUE TITLE
check pdf is image?

### ISSUE THREAD

**Issue by nbao** [tecnickcom/tc-lib-pdf-parser#10]
hello 
After $data = $parser->parse($rawdata);
Is there a method to get the pdf page as object image (Not text data)?
and is there any method to get the pdf form and all field names?

**Comment by nicolaasuni** [comment]
The parse method returns an array of data.
You can traverse the array to extract the required information.
Your request is out of the scope of this library.

**Comment by nbao** [comment]
I think there are 3 types of pdf
- Pdf is created from a scanner so the page object is an image
- Pdf form fill
- pdf text
I think there is method or another way to get all images or get the form field in pfd?
