### ISSUE TITLE
Fatal error: Class 'Com\Tecnick\Pdf\Filter\Filter' not found

### ISSUE THREAD

**Issue by chudhryasif** [tecnickcom/tc-lib-pdf-parser#3]
i am having this error and also there is no Filer file in package

**Comment by nicolaasuni** [comment]
I am unable to reproduce your problem. It is possible that you are trying to parse a PDF document that contains a filter type that has not be implemented.

**Comment by paulina7m** [comment]
I am on wordpress, and included files manually.
`require_once get_template_directory() . '/inc/parts/pdfparser/Process/RawObject.php';
require_once get_template_directory() . '/inc/parts/pdfparser/Process/XrefStream.php';
require_once get_template_directory() . '/inc/parts/pdfparser/Process/Xref.php';
require_once get_template_directory() . '/inc/parts/pdfparser/Exception.php';
require_once get_template_directory() . '/inc/parts/pdfparser/Parser.php';`

And I am also getting the error `Class 'Com\Tecnick\Pdf\Filter\Filter' not found`.

Is this a class that is normally included with other dependencies? It is not present in the folder _src_.

p.s. Here is how I use the parsing functionality:

```

use Com\Tecnick\Pdf\Parser\Parser;

if($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['pdfurl'])){
    $pdfUrl = $_POST['pdfurl'];
    $pdfContent = file_get_contents($pdfUrl);

    $cfg = array('ignore_filter_errors' => true);
    $parser = new Parser($cfg);
    $data = $parser->parse($pdfContent);

    // display data
    echo '<div>'.print_r($data, true).'</div>';
}
```
