### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by TwanoO67** [tecnickcom/tc-lib-pdf-parser#4]
Hello,

It's seems that your repository have problem with his composer definition.
When installing it with: 
 "require": {
        "tecnickcom/tc-lib-pdf-parser": "dev-master"
    },
as you said in the doc, the code pulled is not the last version (actually it's seems to be the first commit of the repo, and not the last...).

So to have the latest commit, We have to use something like that:
"tecnickcom/tc-lib-pdf-parser": "dev-master#5c0a8fdccc17abb3c25ab3dadf752fab01b9ff4b"

And even so, composer has to fetch all of your commits and tags (we can see composer decrementing all versions numbers, during the install process) before finding the good one to install.
Thus, it's taking a very long time to install, and it explode our github rate limit, forcing us to use a github token.

**Comment by nicolaasuni** [comment]
I am unable to reproduce this problem.
Please check the following link and try to update composer.
https://packagist.org/packages/tecnickcom/tc-lib-pdf-parser

**Comment by TwanoO67** [comment]
Hi,

The issue came from the composer.json in your readme

this part should be deleted:

`"repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:tecnickcom/tc-lib-pdf-parser.git"
        }
    ]`

it cause composer to check all the tags in the repo before installation, and it overflow the github anonymous rate limit

**Comment by nicolaasuni** [comment]
Thanks for reporting this.
The composer code in the README is just an example.
Currently this library is in packagist, so you can avoid the repositories section and set the required version.
