### ISSUE TITLE
How can I get raw text of the file?

### ISSUE THREAD

**Issue by giacomomasseron** [tecnickcom/tc-lib-pdf-parser#7]
Hi,  
I need to get the raw text of the file, but I did not understand howto do that.

With `parse` function I get an array, not a string.

**Comment by smalot** [comment]
Hi,
The goal of the `parse` function is to parse the content of the PDF file, not to interprete it.
A PDF can contain text, images, video, 3d object, table and so more.
A single `parse` function can not only returns a text
