### ISSUE TITLE
Class 'Com\Tecnick\Pdf\Parser\Parser' not found

### ISSUE THREAD

**Issue by andrisskutans1** [tecnickcom/tc-lib-pdf-parser#9]
When i open `index.php`, then get error 
`PHP Fatal error:  Uncaught Error: Class 'Com\Tecnick\Pdf\Parser\Parser' not found`

Problem is in this `$pdf = new \Com\Tecnick\Pdf\Parser\Parser($cfg);` code

Could you advice why such error?

**Comment by nicolaasuni** [comment]
Before using the example you must download the vendor dependencies by executing "make deps".
You can also use the "make buildall" to ensure everything is OK.
